modmap:
  - name: Global
    remap:
      CapsLock:
        held: Ctrl_L
        alone: Esc
  - name: Katakana -> Super
    remap:
      KEY_HENKAN: KEY_LEFTMETA
  - name: Right Alt -> Hyper 
    remap:
      RightAlt: F24 
  - name: Right Ctrl -> F23
    remap:
      RightCtrl: F23
