font_family      JetBrainsMono Nerd Font
font_size        13.5

cursor_shape     block

enable_audio_bell yes

confirm_os_window_close 0

background_opacity 1.0

scrollback_lines 10000


# BEGIN_KITTY_THEME
# Tender
include current-theme.conf
# END_KITTY_THEME
