#!/usr/bin/env bash

set -euo pipefail

choice=$(
printf " Lock\n󰒲 Suspend\n󰜉 Reboot\n Shutdown\n Logout" |
fuzzel --dmenu --prompt="Power > "
)

case "$choice" in
	" Lock")
		hyprlock
		;;
	"󰒲 Suspend")
		hyprlock &
		sleep 1
		systemctl suspend
		;;
	"󰜉 Reboot")
		systemctl reboot
		;;
	" Shutdown")
		systemctl poweroff
		;;
	" Logout")
		hyprctl dispatch exit
		;;
esac
