#!/usr/bin/env bash

set -euo pipefail

choice=$(
printf " Lock\n󰒲 Suspend\n󰜉 Reboot\n Shutdown\n Logout" |
fuzzel --dmenu --prompt="Power > "
)

case "$choice" in
    " Lock")
        swaylock
        ;;
    "󰒲 Suspend")
    	swaylock &
    	sleep 1
    	systemctl suspend
    	;;
    "󰜉 Reboot")
        systemctl reboot
        ;;
    " Shutdown")
        systemctl poweroff
        ;;
    " Logout")
        swaymsg exit
        ;;
esac
